server: 192.168.0.32
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://${server}/spring-cloud-sell?characterEncoding=utf-8&userSSL=false
  rabbitmq:
    host: ${server}
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
