auth-server: http://localhost:8089/uaa # sso-server地址
spring:
  application:
    name: client
security:
  oauth2:
    client:
      client-id: merryyou
      client-secret: merryyou
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
      registered-redirect-uri: http://localhost:8088/
    resource:
      token-info-uri:  ${auth-server}/oauth/check_token
logging:
  level:
    org.springframework: info
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  session:
    cookie:
      name: UISESSION