security:
  oauth2:
    client:
      client-id: merryyou
      client-secret: merryyou
    resource:
      token-info-uri: http://localhost:8089/oauth/check_token
logging:
  level:
    org.springframework: debug